---
title: "Setup Instructions"
author: "Ben Woodard"
date: "12/27/2019"
output: html_document
---

*NOTE: Setup an integration in the adobe console* *(https://console.adobe.io/integrations)*  
    *To work with Analytics 2.0 APIs on the Adobe I/O Console, you need to have System Admin rights or developer permissions for your organization. You will receive notification of these rights when granted.*

1. Create an OAuth client:

    A. Navigate to the following URL: https://console.adobe.io/integrations.  
    B. Click the New Integration button.  
    C. Select the Access an API option and then click Continue.  
    D. Under the Experience Cloud section select Adobe Analytics and then select OAuth integration and then click Continue.  
    E. Select New integration and then click Continue.  
    F. Fill out the name, description, redirect URIs and then click Create  Integration.  
      a. name - choose anything you want  
      b. description - if you like yourself, add a description for your future self  
      c. redirect URIs. add "https://adobeanalyticsr\.com/token/result\.html" to the Redirect URI input field.  

2. Add credentials 

    A. Option 1: Create the .Renviron file (preferred)
      1. Add the following items to the file.
        AA_CLIENT_ID = ''
        AA_CLIENT_SECRET = ''
        (optional credentials)
        AA_COMPANY_ID = ''
        AA_REPORTSUITE_ID = ''
      2. Save the file
      3. Restart your R session and reload the package
    B. Option 2: Use the aa_creds() function (possible quick start option)
      1. "client ID"  
      2. "client secret"  
      3. "report suite id"  
      4. "company id"  

    
3. Run the function aa_token()

    A. Log in using your adobe experience cloud login credentials  
    B. After logging in you will be redirected to the token page on adobeanalyticsr.com  
    C. Copy and paste the resulting token into your console where you will see this prompt:  
    `> Enter authorization code: `
  
You should now be able to run your first query function. The most basic query is to pull the list of metrics and/or elements  
`metrics_list <- aa_get_metrics()`.


